### ISSUE TITLE
doesnt fire up when started from chapeau21

### ISSUE THREAD

**Issue by JazzMaster** [chapeaulinux/build-kit#1]
for some reason this script wont fire up correctly from within fc21, requiring use of the internal packaged version to spin chapeau. That version succeeds in building an ISO. Im having key conflict issues on using said from within chapeau22, so will give this another try.No guarantees it will run.

**Comment by vpooley** [comment]
What script are you having problems with?
What version of the build-kit have you downloaded?
What output are you getting, any errors?
