### ISSUE TITLE
need for packaging override

### ISSUE THREAD

**Issue by JazzMaster** [chapeaulinux/build-kit#2]
chapeau needs the build-kit to be put in /usr/bin/, to override the fedora package.This is as per insistance of chapeau support team both on the website and on facebook to use this version.Package preferences should be applied on yum to make chapeau the default version when using chapeau vice fedora. Debian has such a preference, it makes no sense for yum not to have such a preference setting.

**Comment by vpooley** [comment]
What do you mean by "packaging override"?
This makes no sense, what is the issue?
