### ISSUE TITLE
Please add Fedy as a built-in package :D

### ISSUE THREAD

**Issue by andreicristianpetcu** [chapeaulinux/build-kit#4]
Hello, 

Please add Fedy as a built-in package :D
https://satya164.github.io/fedy/

Fedy helps people get software that is not present in Chapeau like Oracle Java, IntelliJ, Popcorntime. It's plugin system is quite simple.

Thank you for building this distro!

**Comment by vpooley** [comment]
Fedy is a tool for Fedora and depends on the rpmfusion-release packages, the Ozon OS software repository and packages created by the Ozon OS project which can potentially conflict with Chapeau's own packages. Fedy is of limited use on Chapeau as much of the key features of Fedy that most of it's users install it for is already taken care of in Chapeau. Sorry, but this won't happen.
